version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - 1521:1521
      - 51521:1521
      - 55500:55500
    environment:
      - ORACLE_PWD=root
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./oracle-volume:/opt/oracle/oradata
    networks:
      - oracle-network

networks:
  oracle-network:

volumes:
  oracle_data:
